/**
 * Simple Direct Test - No Workers Required
 *
 * Tests the core pipeline directly without BullMQ workers
 */

import 'dotenv/config';
import { db } from '../src/lib/db';
import { saveFile } from '../src/lib/storage/local';
import { validateSceneQuality } from '../src/lib/video/quality-check';
import { calculateScenePacing } from '../src/lib/remotion/pacing';
import { getVideoDuration } from '../src/lib/remotion/video-utils';
import { renderNewsVideo } from '../src/lib/remotion/render';
import { prepareRenderAssets } from '../src/lib/remotion/asset-preparation';
import { v4 as uuidv4 } from 'uuid';

// Test inputs
const TEST_AVATAR_PATH = 'C:\\Users\\konra\\Downloads\\Avatar_Video.mp4';
const TEST_SCRIPT = `Breaking tonight: The Senate passed sweeping climate legislation in a narrow 51-50 vote, marking the largest environmental investment in US history. The $369 billion package includes tax credits for electric vehicles, solar panel installations, and heat pump upgrades for American households. Republicans unanimously opposed the bill, calling it government overreach and warning of inflation risks.`;

// Mock scenes (simulating what the AI would generate)
const MOCK_SCENES = [
  {
    id: '1',
    scene_order: 0,
    ticker_headline: 'SENATE PASSES CLIMATE BILL 51-50',
    image_prompt: 'US Senate chamber voting session, dramatic lighting, serious atmosphere, political environment',
    image_url: '', // Will be set to test image
  },
  {
    id: '2',
    scene_order: 1,
    ticker_headline: '$369B FOR CLEAN ENERGY',
    image_prompt: 'Solar panels and wind turbines in a field, renewable energy infrastructure, modern technology',
    image_url: '',
  },
  {
    id: '3',
    scene_order: 2,
    ticker_headline: 'REPUBLICANS OPPOSE SPENDING',
    image_prompt: 'Republican senators in heated discussion, serious faces, government building interior',
    image_url: '',
  },
  {
    id: '4',
    scene_order: 3,
    ticker_headline: 'CLIMATE ACTIVISTS CELEBRATE',
    image_prompt: 'Happy activists celebrating outside Capitol building, holding signs, jubilant atmosphere',
    image_url: '',
  },
];

async function runSimpleTest() {
  console.log('🚀 Simple Direct Test - Quality Checks & Rendering');
  console.log('===================================================\n');

  try {
    // 1. Create test job
    console.log('📝 Step 1: Creating test job...');

    const jobResult = await db.query(
      `INSERT INTO news_jobs (raw_script, status, avatar_script)
       VALUES ($1, $2, $3)
       RETURNING id`,
      [TEST_SCRIPT, 'pending', TEST_SCRIPT] // Use script as avatar_script for simplicity
    );

    const jobId = jobResult.rows[0].id;
    console.log(`✅ Job created: ${jobId}\n`);

    // 2. Copy avatar to storage
    console.log('📁 Step 2: Copying avatar to storage...');

    const avatarFilename = `${jobId}-avatar.mp4`;
    const avatarStoragePath = await saveFile(TEST_AVATAR_PATH, 'avatars', avatarFilename);

    await db.query(
      'UPDATE news_jobs SET avatar_mp4_url = $1 WHERE id = $2',
      [avatarStoragePath, jobId]
    );

    console.log(`✅ Avatar: ${avatarStoragePath}\n`);

    // 3. Create mock scenes in database
    console.log('📸 Step 3: Creating mock scenes...');
    console.log('   (In production, these would be generated by AI + Whisk)\n');

    // For testing, we'll use a placeholder image or just test the validation
    // In reality, you'd generate images via Whisk API here

    for (const scene of MOCK_SCENES) {
      await db.query(
        `INSERT INTO news_scenes (id, job_id, scene_order, ticker_headline, image_prompt, image_url)
         VALUES ($1, $2, $3, $4, $5, $6)`,
        [
          uuidv4(), // Generate proper UUID
          jobId,
          scene.scene_order,
          scene.ticker_headline,
          scene.image_prompt,
          `C:\\Users\\konra\\ObsidianNewsDesk\\images\\test-placeholder.jpg`, // Placeholder
        ]
      );
    }

    console.log(`✅ Created ${MOCK_SCENES.length} mock scenes\n`);

    // 4. Fetch scenes for validation
    console.log('🔍 Step 4: Running quality checks...\n');

    const scenesResult = await db.query(
      `SELECT id, image_url, ticker_headline, scene_order
       FROM news_scenes
       WHERE job_id = $1
       ORDER BY scene_order`,
      [jobId]
    );

    const scenes = scenesResult.rows;

    // 5. Get avatar duration
    const avatarDurationSeconds = await getVideoDuration(avatarStoragePath);
    console.log(`📏 Avatar duration: ${avatarDurationSeconds.toFixed(2)}s\n`);

    // 6. Calculate pacing
    const pacing = calculateScenePacing(avatarDurationSeconds, scenes.length, 30);

    console.log('📐 Pacing calculated:');
    console.log(`   Total duration: ${pacing.totalDurationInSeconds}s (${pacing.totalDurationInFrames} frames)`);
    console.log(`   Hook scenes: ${pacing.hookScenes}`);
    console.log(`   Body scenes: ${pacing.bodyScenes}\n`);

    // 7. Run quality checks
    const qualityCheck = validateSceneQuality(scenes, pacing.sceneTiming, pacing.totalDurationInFrames, 30);

    if (!qualityCheck.passed) {
      console.error('\n❌ QUALITY CHECK FAILED:');
      qualityCheck.errors.forEach(err => console.error(`   - ${err}`));
      throw new Error('Quality check failed - would block render in production');
    }

    if (qualityCheck.warnings.length > 0) {
      console.warn('\n⚠️  Quality warnings (render would still proceed):');
      qualityCheck.warnings.forEach(warn => console.warn(`   - ${warn}`));
    }

    console.log('\n✅ Quality checks PASSED!\n');

    // 8. Test asset preparation (validation only)
    console.log('📦 Step 5: Testing asset preparation...\n');

    try {
      const assetValidation = await prepareRenderAssets(jobId, scenes, avatarStoragePath);

      if (!assetValidation.valid) {
        console.error('❌ Asset validation failed (expected - using placeholder images)');
        console.error('   In production, images would be generated by Whisk API\n');

        console.log('📊 Test Summary:');
        console.log('   ✅ Database operations working');
        console.log('   ✅ Quality check system working');
        console.log('   ✅ Pacing calculation working');
        console.log('   ✅ Avatar file accessible');
        console.log('   ⚠️  Would fail at render (no real images generated)\n');

        console.log('🎯 Next Steps to Complete Full Test:');
        console.log('   1. Generate real images via Whisk API (15-20 min)');
        console.log('   2. Run this test again with real images');
        console.log('   3. Quality checks will pass and render will proceed\n');

        process.exit(0);
      }

      console.log('✅ All assets validated and prepared!\n');

      // 9. OPTIONAL: Render (commented out by default - takes 2-3 minutes)
      // Uncomment to test full rendering

      /*
      console.log('🎥 Step 6: Rendering video...');
      console.log('   This will take 2-3 minutes\n');

      const renderResult = await renderNewsVideo({
        jobId,
        avatarMp4Url: avatarStoragePath,
        scenes,
      });

      console.log('✅ Render complete!');
      console.log(`   Output: ${renderResult.outputPath}`);
      console.log(`   Size: ${(renderResult.sizeInBytes / 1024 / 1024).toFixed(2)} MB`);
      console.log(`   Duration: ${renderResult.durationInSeconds.toFixed(1)}s\n`);
      */

    } catch (error) {
      console.error('⚠️  Asset validation failed:', error instanceof Error ? error.message : String(error));
      console.log('\n📊 Test Summary:');
      console.log('   ✅ Quality checks implemented and working');
      console.log('   ✅ Pacing ensures no black screens');
      console.log('   ✅ Validation runs before render (saves time)');
      console.log('   ⚠️  Need real images to complete render\n');
    }

    console.log('🎉 CORE SYSTEMS TEST COMPLETE!\n');
    process.exit(0);

  } catch (error) {
    console.error('\n❌ TEST FAILED:');
    console.error(error instanceof Error ? error.message : String(error));
    console.error(error instanceof Error ? error.stack : '');
    process.exit(1);
  }
}

runSimpleTest();
