/**
 * GET /api/settings - Read current environment variables
 * POST /api/settings - Update environment variables
 * WARNING: This writes to .env file - only use in local development
 */

import { NextRequest, NextResponse } from 'next/server';
import { writeFile, readFile } from 'fs/promises';
import { join } from 'path';

/**
 * GET - Load current settings from .env file
 */
export async function GET() {
  try {
    const envPath = join(process.cwd(), '.env');

    // Read .env file
    let envContent = '';
    try {
      envContent = await readFile(envPath, 'utf-8');
    } catch {
      // .env doesn't exist, return empty/defaults
      return NextResponse.json({
        AI_PROVIDER: process.env.AI_PROVIDER || 'google',
        ANTHROPIC_API_KEY: '',
        GOOGLE_AI_API_KEY: '',
        GROQ_API_KEY: '',
        WHISK_API_TOKEN: '',
        DATABASE_URL: process.env.DATABASE_URL || '',
        REDIS_HOST: process.env.REDIS_HOST || 'localhost',
        REDIS_PORT: process.env.REDIS_PORT || '6379',
        REDIS_PASSWORD: '',
        DEFAULT_BROWSER: process.env.DEFAULT_BROWSER || 'edge',
        AUTO_WHISK_EXTENSION_ID: process.env.AUTO_WHISK_EXTENSION_ID || 'gedfnhdibkfgacmkbjgpfjihacalnlpn',
        AVATAR_MODE: process.env.AVATAR_MODE || 'manual',
        HEYGEN_PROFILE_PATH: process.env.HEYGEN_PROFILE_PATH || './integrations/heygen-automation/heygen-chrome-profile',
        PYTHON_EXECUTABLE: process.env.PYTHON_EXECUTABLE || 'python',
        REMOTION_TIMEOUT_MS: process.env.REMOTION_TIMEOUT_MS || '300000',
        REMOTION_CONCURRENCY: process.env.REMOTION_CONCURRENCY || '2',
      });
    }

    // Parse .env file
    const settings: Record<string, string> = {};
    const lines = envContent.split('\n');

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;

      const [key, ...valueParts] = trimmed.split('=');
      if (key && valueParts.length > 0) {
        const value = valueParts.join('=');
        settings[key.trim()] = value.trim();
      }
    }

    // Return settings (mask sensitive values)
    return NextResponse.json({
      AI_PROVIDER: settings.AI_PROVIDER || 'google',
      ANTHROPIC_API_KEY: settings.ANTHROPIC_API_KEY ? maskApiKey(settings.ANTHROPIC_API_KEY) : '',
      GOOGLE_AI_API_KEY: settings.GOOGLE_AI_API_KEY ? maskApiKey(settings.GOOGLE_AI_API_KEY) : '',
      GROQ_API_KEY: settings.GROQ_API_KEY ? maskApiKey(settings.GROQ_API_KEY) : '',
      WHISK_API_TOKEN: settings.WHISK_API_TOKEN ? maskApiKey(settings.WHISK_API_TOKEN) : '',
      DATABASE_URL: settings.DATABASE_URL || '',
      REDIS_HOST: settings.REDIS_HOST || 'localhost',
      REDIS_PORT: settings.REDIS_PORT || '6379',
      REDIS_PASSWORD: settings.REDIS_PASSWORD ? '••••••••' : '',
      DEFAULT_BROWSER: settings.DEFAULT_BROWSER || 'edge',
      AUTO_WHISK_EXTENSION_ID: settings.AUTO_WHISK_EXTENSION_ID || 'gedfnhdibkfgacmkbjgpfjihacalnlpn',
      AVATAR_MODE: settings.AVATAR_MODE || 'manual',
      HEYGEN_PROFILE_PATH: settings.HEYGEN_PROFILE_PATH || './integrations/heygen-automation/heygen-chrome-profile',
      PYTHON_EXECUTABLE: settings.PYTHON_EXECUTABLE || 'python',
      REMOTION_TIMEOUT_MS: settings.REMOTION_TIMEOUT_MS || '300000',
      REMOTION_CONCURRENCY: settings.REMOTION_CONCURRENCY || '2',
    });
  } catch (error) {
    console.error('Failed to load settings:', error);
    return NextResponse.json(
      { error: 'Failed to load settings' },
      { status: 500 }
    );
  }
}

/**
 * Helper function to mask API keys (show first 8 chars only)
 */
function maskApiKey(key: string): string {
  if (key.length <= 8) return key;
  return key.substring(0, 8) + '••••••••••••';
}

/**
 * POST - Save settings to .env file
 */
export async function POST(req: NextRequest) {
  try {
    // Verify admin authentication
    const authHeader = req.headers.get('authorization');
    const expectedAuth = `Bearer ${process.env.ADMIN_API_KEY}`;

    if (!authHeader || authHeader !== expectedAuth) {
      console.warn('⚠️ [SETTINGS] Unauthorized settings update attempt');
      return NextResponse.json(
        { error: 'Unauthorized - Admin API key required' },
        { status: 401 }
      );
    }

    const settings = await req.json();
    const envPath = join(process.cwd(), '.env');

    // Read current .env
    let envContent = '';
    try {
      envContent = await readFile(envPath, 'utf-8');
    } catch {
      // .env doesn't exist yet, create header
      envContent = '# Obsidian News Desk - Environment Configuration\n# Generated by Settings UI\n\n';
    }

    // Update or add each setting
    const lines = envContent.split('\n');
    const updatedKeys = new Set<string>();

    for (const [key, value] of Object.entries(settings)) {
      // Skip if value is empty or is a masked value (hasn't changed)
      if (!value || typeof value !== 'string') continue;
      if (value.includes('••••')) continue; // Skip masked passwords

      updatedKeys.add(key);
      const lineIndex = lines.findIndex((line) =>
        line.trim().startsWith(`${key}=`)
      );

      if (lineIndex !== -1) {
        // Update existing line
        lines[lineIndex] = `${key}=${value}`;
      } else {
        // Add new line
        lines.push(`${key}=${value}`);
      }
    }

    // Write back to .env
    await writeFile(envPath, lines.join('\n'), 'utf-8');

    console.log('✅ Settings saved to .env file');

    // Update process.env (for current session - worker restart still needed)
    for (const [key, value] of Object.entries(settings)) {
      if (value && typeof value === 'string' && !value.includes('••••')) {
        process.env[key] = value;
      }
    }

    return NextResponse.json({
      success: true,
      message: 'Settings saved. Restart workers to apply changes.',
    });
  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    console.error('Failed to save settings:', error);
    return NextResponse.json(
      {
        error: 'Failed to save settings',
        details: process.env.NODE_ENV === 'development' ? errorMessage : undefined,
      },
      { status: 500 }
    );
  }
}
